version: "3.7"
services:
  #frontend:
  #  image: eisa/taskman-front
  #  container_name: taskman-front
  #  build: ./frontend
  #  ports:
  #    - "3000:3000"
  #  volumes:
  #    - ./frontend:/app
  #  networks:
  #    - tasknet
  #  restart: on-failure
  #  depends_on:
  #    - api
  db:
    image: "mysql:8"
    container_name: taskman-db
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: taskdb
      MYSQL_ROOT_PASSWORD: ta5ke15a-db
    command: "--default-authentication-plugin=mysql_native_password"
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - tasknet
    restart: always
    security_opt:
      - seccomp:unconfined
  adminer:
    image: "adminer:latest"
    container_name: taskman-adminer
    ports:
      - "8888:8080"
    environment:
      - ADMINER_DEFAULT_SERVER=db
    networks:
      - tasknet
    depends_on:
      - db
    restart: on-failure
networks:
  tasknet:
    driver: bridge
volumes:
  dbdata:
    driver: local